export const styles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '2rem',
    minHeight: 'calc(100vh - 200px)',
    animation: 'fadeIn 0.5s ease-in',
  },
  header: {
    textAlign: 'center',
    marginBottom: '2rem',
    position: 'relative',
  },
  highlight: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  emptyCart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '3rem',
    backgroundColor: '#f8f9fa',
    borderRadius: '12px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    margin: '2rem 0',
    animation: 'fadeIn 0.5s ease-in',
  },
  emptyCartText: {
    fontSize: '1.2rem',
    color: '#666',
    marginBottom: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  continueBtn: {
    padding: '0.8rem 1.5rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '50px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '500',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    '&:hover': {
      backgroundColor: '#45a049',
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 8px rgba(0,0,0,0.2)',
    },
    '&:disabled': {
      backgroundColor: '#cccccc',
      cursor: 'not-allowed',
    },
  },
  table: {
    backgroundColor: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
    marginBottom: '2rem',
    animation: 'slideUp 0.5s ease-out',
  },
  tableHeader: {
    backgroundColor: '#f8f9fa',
    padding: '1rem',
    fontWeight: '600',
    color: '#333',
    borderBottom: '2px solid #e9ecef',
  },
  totalBox: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.5rem',
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    marginBottom: '2rem',
    animation: 'slideUp 0.5s ease-out',
  },
  totalLabel: {
    fontSize: '1.2rem',
    fontWeight: '600',
    color: '#333',
  },
  totalAmount: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#4CAF50',
  },
  actions: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1rem',
    marginTop: '2rem',
  },
  checkoutBtn: {
    padding: '0.8rem 1.5rem',
    backgroundColor: '#2196F3',
    color: 'white',
    border: 'none',
    borderRadius: '50px',
    width: "100%",
    maxWidth: "1800px",
    height: "calc(100vh - 60px)",
    margin: "30px auto",
    padding: "30px",
    background: "#ffffff",
    borderRadius: "16px",
    boxShadow: "0 4px 24px rgba(0, 0, 0, 0.06)",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    textAlign: "center",
    fontSize: "18px",
    color: "#1a1a1a",
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: "1.5px",
    position: "relative",
    "::after": {
      content: '""',
      position: "absolute",
      left: "50%",
      transform: "translateX(-50%)",
      width: "60px",
      height: "3px",
      backgroundColor: "#6c63ff",
      borderRadius: "2px",
    },
  },
  highlight: {
    color: "#374151",
    fontWeight: "bold",
  },
  emptyCart: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "24px",
    padding: "60px 0",
  },
  emptyCartText: {
    color: "#6b7280",
    fontSize: "17px",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  table: {
    width: "100%",
    borderCollapse: "separate",
    borderSpacing: "0 12px",
    flex: "1",
    overflowY: "auto",
    paddingRight: "10px",
    "::-webkit-scrollbar": {
      width: "8px",
    },
    "::-webkit-scrollbar-track": {
      background: "#f1f1f1",
      borderRadius: "4px",
    },
    "::-webkit-scrollbar-thumb": {
      background: "#6c63ff",
      borderRadius: "4px",
    },
    "::-webkit-scrollbar-thumb:hover": {
      background: "#5a52d4",
    },
  },
  tableWrapper: {
    flex: "1",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  tableHeader: {
    padding: "16px 20px",
    textAlign: "left",
    color: "#1a1a1a",
    fontWeight: "400",
    fontSize: "12px",
    borderBottom: "2px solid #f0f0f0",
    textTransform: "uppercase",
    letterSpacing: "1px",
  },
  cartItemRow: {
    backgroundColor: "#ffffff",
    borderRadius: "12px",
    boxShadow: "0 2px 12px rgba(0, 0, 0, 0.04)",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    ":hover": {
      boxShadow: "0 4px 16px rgba(0, 0, 0, 0.08)",
      transform: "translateY(-2px)",
    },
  },
  productCell: {
    padding: "20px",
    width: "30%",
    textAlign: "left",
  },
  productInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  productName: {
    fontSize: "14px",
    color: "#1a1a1a",
    fontWeight: "450",
    letterSpacing: "0.3px",
  },
  attributesCell: {
    padding: "20px",
    width: "20%",
    textAlign: "left",
  },
  attributes: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  attributeContainer: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "10px 14px",
    backgroundColor: "#f8f9fa",
    borderRadius: "8px",
    transition: "all 0.2s ease",
    ":hover": {
      backgroundColor: "#f1f3f5",
    },
  },
  attributeIcon: {
    color: "#6c63ff",
    fontSize: "16px",
    width: "12px",
    opacity: "0.8",
  },
  attributeValue: {
    fontSize: "12px",
    color: "#1a1a1a",
    fontWeight: "500",
    letterSpacing: "0.3px",
  },
  colorBlock: {
    width: "16px",
    height: "16px",
    borderRadius: "6px",
    border: "2px solid #ffffff",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    transition: "all 0.2s ease",
    ":hover": {
      transform: "scale(1.1)",
    },
  },
  quantityCell: {
    padding: "20px",
    width: "15%",
    textAlign: "left",
  },
  quantityControl: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    justifyContent: "flex-start",
  },
  quantityBtn: {
    width: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
    border: "1px solid #e5e7eb",
    backgroundColor: "#ffffff",
    color: "#1a1a1a",
    cursor: "pointer",
    transition: "all 0.2s ease",
    ":hover": {
      backgroundColor: "#f3f4f6",
      borderColor: "#6c63ff",
      color: "#6c63ff",
      transform: "scale(1.05)",
    },
    ":disabled": {
      opacity: "0.5",
      cursor: "not-allowed",
    },
  },
  quantityInput: {
    width: "45px",
    height: "36px",
    textAlign: "center",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    fontSize: "14px",
    color: "#1a1a1a",
    backgroundColor: "#ffffff",
    outline: "none",
    transition: "all 0.2s ease",
    ":focus": {
      borderColor: "#6c63ff",
      boxShadow: "0 0 0 2px rgba(108, 99, 255, 0.1)",
    },
  },
  priceCell: {
    padding: "20px",
    width: "15%",
    textAlign: "left",
  },
  priceContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "4px",
  },
  priceLabel: {
    fontSize: "10px",
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  priceValue: {
    fontSize: "16px",
    color: "#1a1a1a",
    fontWeight: "600",
    letterSpacing: "0.3px",
  },
  actionsCell: {
    padding: "20px",
    width: "20%",
    textAlign: "left",
  },
  actionsContainer: {
    display: "flex",
    gap: "12px",
    justifyContent: "flex-start",
  },
  totalBox: {
    backgroundColor: "#f9fafb",
    padding: "24px",
    borderRadius: "12px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "auto",
    border: "1px solid #e5e7eb",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.04)",
  },
  totalLabel: {
    color: "#6b7280",
    fontSize: "16px",
    fontWeight: "500",
    letterSpacing: "0.3px",
  },
  totalAmount: {
    color: "#6c63ff",
    fontSize: "16px",
    fontWeight: "600",
    letterSpacing: "0.5px",
  },
  actions: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "30px",
    gap: "15px",
  },
  continueBtn: {
    flex: "1",
    padding: "14px 24px",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "400",
    color: "#6c63ff",
    backgroundColor: "transparent",
    border: "2px solid #6c63ff",
    cursor: "pointer",
    transition: "all 0.2s ease",
    letterSpacing: "0.3px",
    ":hover": {
      backgroundColor: "#f3f4f6",
      transform: "translateY(-2px)",
    },
  },
  checkoutBtn: {
    flex: "1",
    padding: "14px 24px",
    borderRadius: "8px",
    fontSize: "16px",
    fontWeight: "400",
    color: "#ffffff",
    backgroundColor: "#6c63ff",
    border: "none",
    cursor: "pointer",
    transition: "all 0.2s ease",
    letterSpacing: "0.3px",
    ":hover": {
      backgroundColor: "#5a52d4",
      transform: "translateY(-2px)",
    },
  },
  actionBtn: {
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    backgroundColor: "transparent",
    border: "none",
    color: "#6b7280",
    cursor: "pointer",
    transition: "all 0.2s ease",
    ":hover": {
      color: "#6c63ff",
      backgroundColor: "#f3f4f6",
      transform: "scale(1.1)",
    },
    ":disabled": {
      opacity: "0.5",
      cursor: "not-allowed",
    },
  },
}; 