export const styles = {
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '1.5rem',
    minHeight: 'calc(100vh - 200px)',
    animation: 'fadeIn 0.5s ease-in',
    backgroundColor: '#f8fafc',
  },
  header: {
    textAlign: 'center',
    marginBottom: '1.5rem',
    position: 'relative',
    padding: '0.75rem 0',
  },
  highlight: {
    color: '#6366f1', // Indigo color
    fontWeight: 'bold',
    textShadow: '0 2px 4px rgba(99, 102, 241, 0.1)',
  },
  emptyWishlist: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem 1.5rem',
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    margin: '1.5rem 0',
    animation: 'fadeIn 0.5s ease-in',
    border: '1px solid #e2e8f0',
  },
  emptyWishlistText: {
    fontSize: '1rem',
    color: '#475569',
    marginBottom: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontWeight: '500',
  },
  continueBtn: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#6366f1',
    color: 'white',
    border: 'none',
    borderRadius: '9999px',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 4px rgba(99, 102, 241, 0.2)',
    '&:hover': {
      backgroundColor: '#4f46e5',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 6px rgba(99, 102, 241, 0.3)',
    },
    '&:disabled': {
      backgroundColor: '#cbd5e1',
      cursor: 'not-allowed',
      transform: 'none',
      boxShadow: 'none',
    },
  },
  table: {
    backgroundColor: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    marginBottom: '1.5rem',
    animation: 'slideUp 0.5s ease-out',
    border: '1px solid #e2e8f0',
  },
  tableHeader: {
    backgroundColor: '#f1f5f9',
    padding: '0.875rem 0.75rem',
    fontWeight: '600',
    color: '#334155',
    borderBottom: '1px solid #e2e8f0',
    fontSize: '0.875rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    textAlign: 'center',
  },
  actions: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '1.5rem',
  },
  wishlistItemRow: {
    transition: 'all 0.2s ease',
    '&:hover': {
      backgroundColor: '#f8fafc',
    },
  },
  productCell: {
    padding: '0.875rem 0.75rem',
  },
  productInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  productName: {
    fontSize: '0.875rem',
    fontWeight: '500',
    color: '#334155',
  },
  priceCell: {
    padding: '0.875rem 0.75rem',
    color: '#6366f1',
    fontWeight: '600',
    fontSize: '0.875rem',
  },
  actionsCell: {
    padding: '0.875rem 0.75rem',
  },
  actionsContainer: {
    display: 'flex',
    gap: '0.5rem',
    justifyContent: 'flex-end',
  },
  '@keyframes fadeIn': {
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
  '@keyframes slideUp': {
    from: { transform: 'translateY(10px)', opacity: 0 },
    to: { transform: 'translateY(0)', opacity: 1 },
  },
}; 